name: Terraform Deployment

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2
          
       # Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Terraform Syntax Validation
      - name: Validate Terraform Syntax
        run: terraform validate

      # Install Checkov (security validation for Terraform)
      - name: Install Checkov
        run: |
          pip install checkov

      # Run Checkov to validate Terraform code for security and policy issues
     # - name: Run Checkov Terraform Scan
      #  run: checkov -d . --skip-check CKV_AWS_23  # You can customize check skip as needed

      # Generate Terraform Plan (in binary format)
      - name: Generate Terraform Plan
        run: terraform plan -out=tfplan

      # Convert Plan to JSON format
      - name: Convert Terraform Plan to JSON
        run: terraform show -json tfplan > plan.json

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: /
          file: doesnexist.json # optional: provide the path for resource to be scanned. This will override the directory if both are provided.
         # check: CKV_AWS_1 # optional: run only a specific check_id. can be comma separated list
        #  skip_check: CKV_AWS_2 # optional: skip a specific check_id. can be comma separated list
          quiet: true # optional: display only failed checks
          soft_fail: false # optional: do not return an error code if there are failed checks

      # Apply Terraform Changes (if plan passes validation)
      - name: Apply Terraform Changes
        if: success()  # Only runs if Checkov passed and returned success
        run: terraform apply -auto-approve tfplan
