name: OPA Terraform Security Scan

on: [push]

jobs:
  opa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OPA
        run: |
          curl -L -o opa https://openbao.org/assets/opa/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/opa

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Format
        run: terraform fmt -check

      - name: Create OPA Policy
        run: |
          mkdir -p policies
          cat > policies/terraform_security.rego << EOL
          package terraform.security

          # Deny resources with overly permissive configurations
          deny[msg] {
              resource := input.resource[_]
              
              # Check for publicly exposed resources
              resource[_].ports[_].ip == "0.0.0.0"
              msg := "Resource exposes port to all interfaces (0.0.0.0)"
          }

          deny[msg] {
              resource := input.resource[_]
              
              # Check for weak or default passwords
              contains(lower(resource[_].content), "password123")
              msg := "Weak or default password detected"
          }

          deny[msg] {
              resource := input.resource[_]
              
              # Check for overly permissive file permissions
              resource[_].file_permission == "0666"
              msg := "Overly permissive file permissions (0666)"
          }
          EOL

      - name: Convert Terraform to JSON
        run: terraform show -json > tfplan.json

      - name: Run OPA Scan
        run: |
          opa eval --format pretty \
            -d tfplan.json \
            -d policies/terraform_security.rego \
            "data.terraform.security.deny"
