name: Terraform Deployment

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2
          
       # Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Terraform Syntax Validation
      - name: Validate Terraform Syntax
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Show
        run: terraform show -json tfplan > tfplan.json

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
         framework: terraform
          
      # Apply Terraform Changes (if plan passes validation)
      - name: Apply Terraform Changes
        if: success()  # Only runs if Checkov passed and returned success
        run: terraform apply -auto-approve tfplan
