name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2
          
       # Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Terraform Syntax Validation
      - name: Validate Terraform Syntax
        run: terraform validate

      # Install Checkov (security validation for Terraform)
      - name: Install Checkov
        run: |
          pip install checkov

      # Run Checkov to validate Terraform code for security and policy issues
      - name: Run Checkov Terraform Scan
        run: checkov -d . --skip-check CKV_AWS_23  # You can customize check skip as needed

      # Plan Terraform Changes
      - name: Plan Terraform Changes
        run: terraform plan

      # Apply Terraform Changes
      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
